# Generated by Django 3.0 on 2022-03-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empCity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
